# CI test workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      # uses: microsoft/powerplatform-actions/who-am-i@v0
      uses: ./microsoft/powerplatform-actions/who-am-i
      with:
        environment-url: 'https://user8-build.crm.dynamics.com/'
        user-name: 'user8@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: pack-solution action
      # uses: microsoft/powerplatform-actions/pack-solution@v0
      uses: ./microsoft/powerplatform-actions/pack-solution
      with:
        solution-folder: 'solutions/emptySolution'
        solution-file: 'out/CI/emptySolution.zip'
        solution-type: 'Unmanaged'

    - name: import-solution action
      # uses: microsoft/powerplatform-actions/import-solution@v0
      uses: ./microsoft/powerplatform-actions/import-solution
      with:
        environment-url: 'https://user8-build.crm.dynamics.com/'
        user-name: 'user8@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: 'out/CI/emptySolution.zip'
        force-overwrite: true

    - name: export-solution action
      # uses: microsoft/powerplatform-actions/export-solution@v0
      uses: ./microsoft/powerplatform-actions/export-solution
      with:
        environment-url: 'https://user8-build.crm.dynamics.com/'
        user-name: 'user8@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: emptySolution
        solution-output-file: 'solution1.zip'
        working-directory: 'out/CI'

    - name: unpack-solution action
      # uses: microsoft/powerplatform-actions/unpack-solution@v0
      uses: ./microsoft/powerplatform-actions/unpack-solution
      with:
        solution-file: 'out/CI/solution1.zip'
        solution-folder: 'out/CI/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true
