# CI workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      # uses: microsoft/powerplatform/actions/who-am-i
      uses: ./microsoft/powerplatform/actions/who-am-i
      with:
        environment-url: 'https://davidjenD365-1.crm.dynamics.com'
        user-name: 'davidjen@davidjenD365.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      # uses: microsoft/powerplatform/actions/export-solution
      uses: ./microsoft/powerplatform/actions/export-solution
      with:
        environment-url: 'https://davidjenD365-1.crm.dynamics.com'
        user-name: 'davidjen@davidjenD365.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: emptySolution
        solution-output-file: 'solution1.zip'
        working-directory: 'out/CI'

    - name: unpack-solution action
      # uses: microsoft/powerplatform/actions/unpack-solution
      uses: ./microsoft/powerplatform/actions/unpack-solution
      with:
        solution-input-file: 'out/CI/solution1.zip'
        solution-target-folder: 'out/CI/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true
