name: CI

on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sample-flow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
      fail-fast: false
    env:
      RUNNER_DEBUG: 1
      WF_CLOUD: UsGovDod

      WF_USERNAME: mstest_dataverse@testtestdodvalidation.onmicrosoft.us
      # set repo secret with password: PASSWORD_PPDEVTOOLS

      # WF_APPID: 8a7729e0-2b71-4919-a89a-c789d0a9720a
      # WF_TENANT_ID: 3041a058-5110-495a-a575-b2a5571d9eac
      # set repo secret with appID's client secret: CLIENT_SECRET_PPDEVTOOLS

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: create ephemeral test environment
      uses: microsoft/powerplatform-actions/create-environment@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      id: test-environment
      env:
        PP_SRC_ENV_NAME: ${{ format('dj-sample-{0}', runner.os) }}
      with:
        cloud: ${{ env.WF_CLOUD }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        # app-id: ${{ env.WF_APPID }}
        # tenant-id: ${{ env.WF_TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        name: ${{ env.PP_SRC_ENV_NAME }}
        type: Sandbox
        region: unitedstates
        domain: ${{ env.PP_SRC_ENV_NAME }}

    - name: who-am-i
      uses: microsoft/powerplatform-actions/who-am-i@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      with:
        cloud: ${{ env.WF_CLOUD }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_DOD }}
        # app-id: ${{ env.WF_APPID }}
        # tenant-id: ${{ env.WF_TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        environment-url: ${{ steps.test-environment.outputs.environment-url }}

    - name: pack-solution
      uses: microsoft/powerplatform-actions/pack-solution@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      with:
        solution-folder: 'solutions/Covid19Screening-staged'
        solution-file: out/CI/solutions/Covid19Screening.zip
        solution-type: 'Unmanaged'

    - name: import-solution
      uses: microsoft/powerplatform-actions/import-solution@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      with:
        cloud: ${{ env.WF_CLOUD }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_DOD }}
        # app-id: ${{ env.WF_APPID }}
        # tenant-id: ${{ env.WF_TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        environment-url: ${{ steps.test-environment.outputs.environment-url }}
        solution-file: out/CI/solutions/Covid19Screening.zip
        run-asynchronously: true
        force-overwrite: true

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      with:
        cloud: ${{ env.WF_CLOUD }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_DOD }}
        # app-id: ${{ env.WF_APPID }}
        # tenant-id: ${{ env.WF_TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        environment-url: ${{ steps.test-environment.outputs.environment-url }}
        solution-name: Covid19Screening
        managed: true
        run-asynchronously: true
        solution-output-file: out/ship/Covid19Screening.zip

    - name: delete-solution
      uses: microsoft/powerplatform-actions/delete-solution@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      with:
        cloud: ${{ env.WF_CLOUD }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_DOD }}
        # app-id: ${{ env.WF_APPID }}
        # tenant-id: ${{ env.WF_TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        environment-url: ${{ steps.test-environment.outputs.environment-url }}
        solution-name: Covid19Screening

    - name: delete ephemeral test environment
      if: always() # Clean up created environments even on failed run
      uses: microsoft/powerplatform-actions/delete-environment@d80136bf425c8cd66db9f5a774bb7b8ebecfb76c
      with:
        cloud: ${{ env.WF_CLOUD }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        # app-id: ${{ env.WF_APPID }}
        # tenant-id: ${{ env.WF_TENANT_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        environment-url: ${{ steps.test-environment.outputs.environment-url }}

    - name: Determine logs folder glob
      id: get-logs-glob
      uses: actions/github-script@v6
      if: always()
      with:
        result-encoding: string
        script: |
          const path = require('path')
          const os = require('os')
          return `${path.resolve('${{ github.workspace }}', os.platform() === 'win32' ?  '../../..' : '../..', '_actions/microsoft/powerplatform-actions')}/**/dist/pac*/tools/logs/pac-log.txt`

    # - name: showRes
    #   if: always()
    #   run: echo "${{steps.get-logs-glob.outputs.result}}"

    - name: Upload pac CLI logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: pac-cli-log ${{ matrix.os }}
        path: "${{steps.get-logs-glob.outputs.result}}"
