name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      # uses: microsoft/powerplatform-actions/who-am-i@v0
      uses: ./microsoft/powerplatform-actions/who-am-i
      with:
        environment-url: 'https://user9-dev.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      # uses: microsoft/powerplatform-actions/export-solution@v0
      uses: ./microsoft/powerplatform-actions/export-solution
      with:
        environment-url: 'https://user9-dev.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: Covid19Screening
        solution-output-file: 'Covid19Screening.zip'
        working-directory: 'out/CI'

    - name: unpack-solution action
      # uses: microsoft/powerplatform-actions/unpack-solution@v0
      uses: ./microsoft/powerplatform-actions/unpack-solution
      with:
        solution-file: 'out/CI/Covid19Screening.zip'
        solution-folder: 'out/CI/solutions/Covid19Screening'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: pack-solution action
      # uses: microsoft/powerplatform-actions/pack-solution@v0
      uses: ./microsoft/powerplatform-actions/pack-solution
      with:
        solution-folder: 'out/CI/solutions/Covid19Screening'
        solution-file: 'out/CI/solutions/Covid19Screening.zip'
        solution-type: 'Unmanaged'

    - name: import-solution action
      # uses: microsoft/powerplatform-actions/import-solution@v0
      uses: ./microsoft/powerplatform-actions/import-solution
      with:
        environment-url: 'https://user9-build.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: 'out/CI/solutions/Covid19Screening.zip'
        force-overwrite: true

    - name: List Covid19Screening solution
      run: |
        cmd /c "dir /s /ogen /b out\CI\solutions\Covid19Screening"

    - name: Create PR branch
      run: |
        mkdir out\staging
        pushd out\staging
        git clone https://github.com/davidjenni/pp-actions-sample.git sample
        cd sample
        $branch = (Get-Date -Format "yyyyMMdd-HHmm")
        git config --local user.email "davidjen@davidjend365.onmicrosoft.com"
        git config --local user.name "David"
        git checkout -b covid19-$($branch)
        echo "refreshing checked in solution..."
        rm -Recurse -Force .\solutions\Covid19Screening -ErrorAction SilentlyContinue
        Copy-Item -Path .\out\CI\solutions\Covid19Screening\ -Destination .\solutions\Covid19Screening\ -Recurse -Force
        git add .\solutions\Covid19Screening
        git status
        git commit -m"PR for exported solution $($branch)"
        git push origin $branch
        popd
