name: release-screening-solution

on:
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      # uses: microsoft/powerplatform-actions/pack-solution@v0
      uses: ./microsoft/powerplatform-actions/pack-solution
      with:
        solution-folder: 'solutions/Covid19Screening-staged'
        solution-file: out/CI/solutions/Covid19Screening.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      # uses: microsoft/powerplatform-actions/import-solution@v0
      uses: ./microsoft/powerplatform-actions/import-solution
      with:
        environment-url: 'https://user9-build.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: out/CI/solutions/Covid19Screening.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      # uses: microsoft/powerplatform-actions/export-solution@v0
      uses: ./microsoft/powerplatform-actions/export-solution
      with:
        environment-url: 'https://user9-build.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: Covid19Screening
        managed: true
        solution-output-file: out/ship/Covid19Screening.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/Covid19Screening.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Import solution to staging env
      # uses: microsoft/powerplatform-actions/import-solution@v0
      uses: ./microsoft/powerplatform-actions/import-solution
      with:
        # TODO: switch url to the test/staging one
        environment-url: 'https://user9-build.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: out/release/Covid19Screening.zip
        force-overwrite: true
        publish-changes: true
